import React, { FC, useMemo, ReactElement } from 'react';
import type { Metadata } from 'next';
import Head from 'next/head';
import { Inter } from 'next/font/google';

import {
  ConnectionProvider,
  WalletProvider,
} from '@solana/wallet-adapter-react';

import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';

import { WalletModalProvider } from '@solana/wallet-adapter-react-ui';

import { clusterApiUrl } from '@solana/web3.js';

import type { AppProps } from 'next/app';
import '../app/globals.css'; // Global CSS for your app

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Martin Portfolio',
  description: 'Generated by create next app',
};

const App: FC<AppProps> = ({
  Component,
  pageProps,
}: AppProps): ReactElement => {
  const network = WalletAdapterNetwork.Devnet; // You can change to 'mainnet-beta', 'testnet', etc.

  const endpoint = useMemo(() => clusterApiUrl(network), [network]);

  const wallets = useMemo(() => [], [network]);

  return (
    <>
      <Head>
        <title>Richard the penguin</title>
        {/* handle meta for UI when this link shared */}
        <meta name='description' content='Your page description' />
        <meta property='og:title' content='Your Page Title' />
        <meta property='og:description' content='Your page description' />
        <meta property='og:image' content='https://example.com' />
        <meta property='og:url' content='https://example.com' />
      </Head>
      <ConnectionProvider endpoint={endpoint}>
        <WalletProvider wallets={wallets}>
          <WalletModalProvider>
            {/* Render the current page */}
            <Component {...pageProps} />
          </WalletModalProvider>
        </WalletProvider>
      </ConnectionProvider>
    </>
  );
};

export default App;
